"""
Django settings for Volcano project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k+k21s28)+wqbq*y)#$r1oi9n5269)k)l&)w_d9xwmiyu&-n#^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
#descpmentaar---------------------------------------
ALLOWED_HOSTS = ['134.122.125.35', '127.0.0.1', 'localhost']
DOMAIN = '134.122.125.35'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'corsheaders',
    'volcanoApp',
    'psycopg2',
    'rest_framework',
    'knox',
    'rest_framework.authtoken',
    'django_filters',
    'crispy_forms',
    'channels',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

CHANNEL_LAYERS = {
    'default': {
        ### Method 1: Via redis lab
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [
        #       'redis://h:<password>;@<redis Endpoint>:<port>' 
        #     ],
        # },

        ### Method 2: Via local Redis
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #      "hosts": [('127.0.0.1', 6379)],
        # },

        ### Method 3: Via In-memory channel layer
        ## Using this method.
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}

ROOT_URLCONF = 'Volcano.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Volcano.wsgi.application'
ASGI_APPLICATION = 'Volcano.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'volcano2',
        'HOST' : '127.0.0.1',
        'USER' : 'lonccos',
        'PASSWORD' : 'sistemas',
        'PORT' : '5432',    
    },

}
'''
    'mongodb': {
        'ENGINE': 'djongo',
        'ENFORCE_SCHEMA': False,
        'NAME': 'volcanojson',  # Nombre de tu base de datos MongoDB.
        'CLIENT': {
            'host': 'localhost',  # Cambia a la ubicación de tu servidor MongoDB si es necesario.
        }
    }
'''

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',)
    ,
    #'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated',],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
     'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True

CORS_ALLOWED_ORIGINS = [
    "https://134.122.125.35",
    "http://localhost:3000",
    "http://localhost:8001",
    "http://localhost:8004",
    "http://127.0.0.1:9000",
]

CORS_ORIGIN_WHITELIST = [
    "https://134.122.125.35",
    "http://localhost:3000",
    "http://localhost:8001",
    "http://localhost:8004",
    "http://127.0.0.1:9000",
]
CORS_ORIGIN_ALLOW_ALL = True
import os
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'Volcano/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
MEDIA_URL = 'volcanoApp/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jveras@unsa.edu.pe'
EMAIL_HOST_PASSWORD = 'vnjprxaehqoggxtu'

TELEGRAM_TOKEN = "6319696449:AAHMMT6jxs5FCU53avvefZDdmK7ZCkZPy_M"
TELEGRAM_CHANNEL_CHAT_ID = "-1001945707253"

TWILIO_WSP_ACCOUNT_SID = 'AC4be8d2722d0fd93e4d4ee9560b82d91e'
TWILIO_WSP_AUTH_TOKEN = '013844f3eed7d5063cb8b8f4419dc28e'

import firebase_admin
from firebase_admin import credentials
import json
cred_dict = {
    "type": "service_account",
    "project_id": "proyecto-sabancaya",
    "private_key_id": "02a91dcc084ff0d5251f2142403d799d838b23cc",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLEQmjwiuDgi2w\nqUu6TU/y3RnP6f+GkKJEist12Dt/mqjDJYV3puGkEBQnsTkO7luydvPbpmesaCde\nIy4nS7zS+Okv8k/wLRkyM9nNNnXBtNcSBfZu+/jWaAbntT6J6b2frqA/dq+UD+V7\nTsy47D5i3NMUBxEa5EYMw48zvIGg4BI8t2wWh9iHVNWcPK2a6ELT/tZso6wbMoNP\nQ85GiNfRj4v5NXVdfGwSu6CAsz7zjmeJufbYM07sOImfJmNoqZYBlIkdUa56nAo4\n9KODNem2PVBy8ZyrCarfRYLc28AD6lgirjcaUo+gqj9isOY91Lbd9Jw0VzPJgTwG\n1Wx8OiA9AgMBAAECggEAJfC9PRZAhI3sRPtgnYKn6x/B3J2jAyyfUNCg4pf/x9/o\n46stRHWO55UkeuULHN3OjqnYdqPg7263WkiW7TsioMVmZjGvG1gFwuI6sbOY7VQB\nMgogqMxVyhN+JMkxkdl09zKMmMbvV6nfrboDmJJ1Non9Oxr16HEZoHViWl+AVcLq\nkmINJCwQKXHfC6aTiSY/UpSKWEEWhvKSyN3etBfRkxYSG9Li/egSuCaTgxonCT8g\nGM7Rv2WXWq1NbNAQ5ryKdEDjCMs6pFhXyTzJ9IwUhNLzbENXW+l8GqXmCQQifXSu\ngA8h9oJdniO6BdcL8p3kffe7R/fCXjwGLL93LFt8+QKBgQDqMTFOrD9HW0MMdZ/Y\nL8uUzCH1+0O1Eq0ytpU92F77x+h/eRapUv5rt05t8grM7RGx9YNBc/CRSQ7+OTGG\nzTuVpvIPAysQtiKaxrvXz1b+DTSRTqlPAwPNfvMW7kWv4/p3EyBtFUlKhmW1oGME\nf72CivSVfREKZogl+wEgvqTjCQKBgQDd+dre/NeINUiT59pNJHOAaQJ5YvH9GyLi\nq0krXKCbeVGObcDwdGfA+R8LRPksseOfJFpdOP9I2dX44qlGBiJ0mc7p8J/LS8TB\nR4dCtU6xWldV+GCq9Whsw3pq/jHjKZutbRQELgRxaNQnoYf7OYNDxwCwp1TqOMJK\nfaIW7EUclQKBgQDKESXtLtvuksT4ZClGXH745WVMG7/g5buBbV66HQ5fiq6GBpHS\nCaUyhdhrLxO4m7jP5vmYqRPiF7qTCgA8wqptxr1GzMIEylJzX5RGckUqMXSxB8E4\nRm6qiaXvnCmOyVOcGGm7FUnGvs3VeAzXneyDTagZr+7bHXrN4pSnjzcwGQKBgHkS\nqODrhBvVBEs4MQfWk/E8VY8j+t2VCYgc6QHvueJTX7qR/qSouVa2Csq4yjgopwDM\ncUVbq1JvDph7+NwqyGxU4FkVV/Mo1p6dhxdJkSyHHA/WM9PLmzOHw6PMFiXTMgh7\n8Gj/OIkrJlyfbG4IxqIXTzcLbfN7Fe5PbDOYl3GpAoGARdH72h5dODaVAH+176u5\nbTH/DdgOIsaHIPf7WBTiYJjp5xhGEpScmxVtRsY586LdywP8sAF6o546j6BBsJBP\nhs+CUgr3oiQ5ro6vBHewWy39io1L9Et76azJcdu26pFp6YXXG/4HRBc4HN3RrDpV\nHFm234DwSRZ8NBdvpDQP1uo=\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-adminsdk-98bi0@proyecto-sabancaya.iam.gserviceaccount.com",
    "client_id": "106776977131620523888",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-98bi0%40proyecto-sabancaya.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
}

cred = credentials.Certificate(cred_dict)
firebase_admin.initialize_app(cred)