# Generated by Django 4.2.3 on 2023-08-18 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volcanoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesegmentation',
            name='datecreationimg',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='roll',
        ),
        migrations.AlterField(
            model_name='alert',
            name='datecreationalert',
            field=models.TimeField(auto_now_add=True, db_column='dateCreationAlert'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='idalertconf',
            field=models.ForeignKey(db_column='idAlertConf', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.alertconfiguration'),
        ),
        migrations.AlterField(
            model_name='alertconfiguration',
            name='datecreationalertconf',
            field=models.TimeField(auto_now_add=True, db_column='dateCreationAlertConf'),
        ),
        migrations.AlterField(
            model_name='blob',
            name='datecreationblob',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationBlob'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='datecreationevent',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationEvent'),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='datecreationmet',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationMet'),
        ),
        migrations.AlterField(
            model_name='station',
            name='datecreationstat',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationStat'),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='datecreationtempser',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationTempSer'),
        ),
        migrations.AlterField(
            model_name='userp',
            name='datecreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userp',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userp',
            name='state',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='userp',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
