# Generated by Django 4.2.3 on 2023-08-18 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0002_remove_imagesegmentation_datecreationimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesegmentation',
            name='datecreationimg',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationImg', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
