# Generated by Django 4.2.3 on 2023-08-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0003_imagesegmentation_datecreationimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='imagecover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
