# Generated by Django 4.2.3 on 2023-08-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0004_alter_userp_imagecover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userp',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userp',
            name='username',
        ),
        migrations.AlterField(
            model_name='alert',
            name='idalertconf',
            field=models.ForeignKey(db_column='idAlertConf', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.alertconfiguration'),
        ),
    ]
