# Generated by Django 4.2.3 on 2023-08-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0005_remove_userp_adress_remove_userp_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='comment',
            field=models.CharField(default='', max_length=8192),
            preserve_default=False,
        ),
    ]
