# Generated by Django 4.2.3 on 2023-08-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0006_userp_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userp',
            old_name='firstname',
            new_name='username',
        ),
    ]
