# Generated by Django 4.2.3 on 2023-08-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0007_rename_firstname_userp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='institution',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
