# Generated by Django 4.2.3 on 2023-09-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0009_alter_userp_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='idblob',
            field=models.CharField(db_column='idBlob', max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mask',
            name='idmask',
            field=models.CharField(db_column='idMask', max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='idmetereorologicaldata',
            field=models.CharField(db_column='idMetereorologicalData', max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='idtemporaryseries',
            field=models.CharField(db_column='idTemporarySeries', max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userp',
            name='type',
            field=models.IntegerField(default=3),
        ),
    ]
