# Generated by Django 4.2.3 on 2023-09-05 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0010_alter_blob_idblob_alter_mask_idmask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='areatmask',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='directiontmask',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='filenametmask',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='heightmask',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='perimetertmask',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='starttimetmask',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='xcentroidtmask',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='ycentroidtmask',
        ),
        migrations.AddField(
            model_name='mask',
            name='directionmask',
            field=models.TextField(db_column='directionmask', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mask',
            name='filenamemask',
            field=models.TextField(db_column='fileNamemask', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mask',
            name='heighmask',
            field=models.FloatField(db_column='heighmask', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mask',
            name='starttimemask',
            field=models.DateTimeField(db_column='startTimemask', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
