# Generated by Django 4.2.3 on 2023-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0011_remove_mask_areatmask_remove_mask_directiontmask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='directionblob',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='filenameblob',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='heightblob',
        ),
        migrations.RemoveField(
            model_name='blob',
            name='starttimeblob',
        ),
        migrations.AddField(
            model_name='blob',
            name='areatblob',
            field=models.FloatField(db_column='areablob', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blob',
            name='indblob',
            field=models.CharField(db_column='indblob', default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blob',
            name='perimetertblob',
            field=models.FloatField(db_column='perimeterblob', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blob',
            name='xcentroidtblob',
            field=models.FloatField(db_column='xCentroidblob', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blob',
            name='ycentroidtblob',
            field=models.FloatField(db_column='yCentroidblob', default=1),
            preserve_default=False,
        ),
    ]
