# Generated by Django 4.2.3 on 2023-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0012_remove_blob_directionblob_remove_blob_filenameblob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='indmask',
            field=models.CharField(db_column='indmask', default=1, max_length=1),
            preserve_default=False,
        ),
    ]
