# Generated by Django 4.2.3 on 2023-09-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0014_alter_alertconfiguration_messagetemplateconfalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='idstation',
            field=models.CharField(db_column='idStation', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='idvolcano',
            field=models.CharField(db_column='idVolcano', max_length=10, primary_key=True, serialize=False),
        ),
    ]
