# Generated by Django 4.2.3 on 2023-09-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0015_alter_station_idstation_alter_volcano_idvolcano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userp',
            old_name='username',
            new_name='names',
        ),
    ]
