# Generated by Django 4.2.3 on 2023-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0016_rename_username_userp_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
