# Generated by Django 4.2.3 on 2023-09-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0017_alter_userp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userp',
            name='imagecover',
        ),
    ]
