# Generated by Django 4.2.3 on 2023-09-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0018_remove_userp_imagecover'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='imagecover',
            field=models.ImageField(blank=True, upload_to='imagenes/'),
        ),
    ]
