# Generated by Django 4.2.3 on 2023-09-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0019_userp_imagecover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryseries',
            name='ideventtype',
            field=models.ForeignKey(db_column='idEventType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.eventtype'),
        ),
        migrations.AlterField(
            model_name='userp',
            name='imagecover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
