# Generated by Django 4.2.3 on 2023-09-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0020_alter_temporaryseries_ideventtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='ideventtype',
            field=models.CharField(db_column='idEventType', max_length=10, primary_key=True, serialize=False),
        ),
    ]
