# Generated by Django 4.2.3 on 2023-10-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0021_alter_eventtype_ideventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='idphoto',
            field=models.ForeignKey(blank=True, db_column='idPhoto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.imagesegmentation'),
        ),
    ]
