# Generated by Django 4.2.3 on 2023-10-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0022_alter_mask_idphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='idstation',
        ),
        migrations.AddField(
            model_name='imagesegmentation',
            name='idstation',
            field=models.ForeignKey(db_column='idStation', default='SAB', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.station'),
            preserve_default=False,
        ),
    ]
