# Generated by Django 4.2.3 on 2023-10-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0023_remove_mask_idstation_imagesegmentation_idstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorologicaldata',
            name='idstation',
            field=models.ForeignKey(db_column='idStation', default=9, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.station'),
            preserve_default=False,
        ),
    ]
