# Generated by Django 4.2.3 on 2023-10-11 09:50

from django.db import migrations, models
import volcanoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0024_meteorologicaldata_idstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='idphoto',
        ),
        migrations.AlterField(
            model_name='imagesegmentation',
            name='idphoto',
            field=models.CharField(db_column='idPhoto', max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='idvolcano',
            field=models.CharField(db_column='idVolcano', default=volcanoApp.models.Volcano.generate_default_idvolcano, max_length=10, primary_key=True, serialize=False),
        ),
    ]
