# Generated by Django 4.2.3 on 2023-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0027_alter_imagesegmentation_idphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='idmask',
            field=models.CharField(db_column='idMask', max_length=22, primary_key=True, serialize=False),
        ),
    ]
