# Generated by Django 4.2.3 on 2023-10-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0029_alter_mask_idmask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='idmask',
            field=models.OneToOneField(db_column='idMask', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='volcanoApp.imagesegmentation'),
        ),
    ]
