# Generated by Django 4.2.3 on 2023-10-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0030_alter_mask_idmask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volcano',
            name='idvolcano',
            field=models.CharField(db_column='idVolcano', max_length=9, primary_key=True, serialize=False),
        ),
    ]
