# Generated by Django 4.2.3 on 2023-10-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0032_alter_volcano_idvolcano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volcano',
            name='idvolcano',
            field=models.CharField(blank=True, db_column='idVolcano', max_length=9, primary_key=True, serialize=False),
        ),
    ]
