# Generated by Django 4.2.3 on 2023-10-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0033_alter_volcano_idvolcano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='idvolcano',
        ),
        migrations.RemoveField(
            model_name='meteorologicaldata',
            name='idvolcano',
        ),
        migrations.RemoveField(
            model_name='temporaryseries',
            name='idvolcano',
        ),
        migrations.AddField(
            model_name='station',
            name='idvolcano',
            field=models.ForeignKey(blank=True, db_column='idVolcano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.volcano'),
        ),
    ]
