# Generated by Django 4.2.3 on 2023-10-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0034_remove_mask_idvolcano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('tablenamemap', models.CharField(db_column='tablenameMap', max_length=50, primary_key=True, serialize=False)),
                ('attributeskeysmap', models.JSONField(db_column='attributeskeysMap')),
            ],
        ),
    ]
