# Generated by Django 4.2.3 on 2023-10-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0035_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blob',
            name='idblob',
            field=models.CharField(db_column='idBlob', max_length=23, primary_key=True, serialize=False),
        ),
    ]
