# Generated by Django 4.2.3 on 2023-10-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0036_userp_phone_alter_blob_idblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryseries',
            name='indtempser',
            field=models.IntegerField(db_column='indTempSer', null=True),
        ),
    ]
