# Generated by Django 4.2.3 on 2023-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0037_temporaryseries_indtempser'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfiguration',
            name='startalert',
            field=models.SmallIntegerField(db_column='startAlertConf', default=1),
            preserve_default=False,
        ),
    ]
