# Generated by Django 4.2.3 on 2023-11-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0038_alertconfiguration_startalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='statehistory',
            field=models.SmallIntegerField(db_column='statehistory', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='stateevent',
            field=models.SmallIntegerField(db_column='stateEvent'),
        ),
    ]
