# Generated by Django 4.2.3 on 2023-11-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0039_history_statehistory_alter_eventtype_stateevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='statemask',
            field=models.SmallIntegerField(db_column='statemask', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='statehistory',
            field=models.SmallIntegerField(db_column='stateHistory'),
        ),
    ]
