# Generated by Django 4.2.3 on 2023-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0040_mask_statemask_alter_history_statehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
