# Generated by Django 4.2.3 on 2023-11-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0042_alter_userp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
