# Generated by Django 4.2.3 on 2023-11-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0043_alter_userp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='indmet',
            field=models.IntegerField(blank=True, db_column='indMet', null=True),
        ),
    ]
