# Generated by Django 4.2.3 on 2023-11-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0044_alter_meteorologicaldata_indmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='indmask',
            field=models.SmallIntegerField(db_column='indmask'),
        ),
    ]
