# Generated by Django 4.2.3 on 2023-11-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0045_alter_mask_indmask'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorologicaldata',
            name='jsonmet',
            field=models.JSONField(db_column='jsonMet', default={}),
            preserve_default=False,
        ),
    ]
