# Generated by Django 4.2.3 on 2023-11-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0049_alter_imagesegmentation_idphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='idblob',
            field=models.CharField(blank=True, db_column='idBlob', max_length=23, primary_key=True, serialize=False),
        ),
    ]
