# Generated by Django 4.2.3 on 2023-11-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0050_alter_blob_idblob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='messagealert',
            field=models.TextField(blank=True, db_column='messageAlert'),
        ),
        migrations.AlterField(
            model_name='blob',
            name='idblob',
            field=models.CharField(blank=True, db_column='idBlob', max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='ideventtype',
            field=models.CharField(db_column='idEventType', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='idstation',
            field=models.CharField(blank=True, db_column='idStation', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='ideventtype',
            field=models.ForeignKey(db_column='idEventType', default='00', on_delete=django.db.models.deletion.CASCADE, to='volcanoApp.eventtype'),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='idtemporaryseries',
            field=models.CharField(blank=True, db_column='idTemporarySeries', max_length=21, primary_key=True, serialize=False),
        ),
    ]
