# Generated by Django 4.2.3 on 2023-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0051_alter_alert_messagealert_alter_blob_idblob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='imageprofile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
