# Generated by Django 4.2.3 on 2023-11-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0052_userp_imageprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashdispersion',
            fields=[
                ('idashdispersion', models.CharField(db_column='idAshDispersion', max_length=21, primary_key=True, serialize=False)),
                ('jsonashdisp', models.JSONField(db_column='jsonAshdisp')),
                ('starttimeashdisp', models.DateTimeField(db_column='startTimeAshdisp')),
                ('urlfileashdisp', models.TextField(db_column='urlfileAshdisp')),
                ('idnoticeashdisp', models.CharField(db_column='idNoticeAshdisp', max_length=10)),
                ('idtypeashdisp', models.CharField(choices=[('OBSERVED', ''), ('FORECAST', '')], max_length=20)),
                ('statemet', models.SmallIntegerField(db_column='stateMet')),
                ('datecreationmet', models.DateTimeField(auto_now_add=True, db_column='dateCreationMet')),
                ('idvolcano', models.ForeignKey(blank=True, db_column='idVolcano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.volcano')),
            ],
            options={
                'db_table': 'AshDispersion',
            },
        ),
        migrations.CreateModel(
            name='Ashfallprediction',
            fields=[
                ('idashfallprediction', models.CharField(db_column='idAshfallprediction', max_length=21, primary_key=True, serialize=False)),
                ('starttimeashfall', models.DateTimeField(db_column='startTimeAshfall')),
                ('stateashfall', models.SmallIntegerField(db_column='stateAshfall')),
                ('datecreationashfall', models.DateTimeField(auto_now_add=True, db_column='dateCreationAshfall')),
                ('idvolcano', models.ForeignKey(blank=True, db_column='idVolcano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.volcano')),
            ],
            options={
                'db_table': 'AshFallPrediction',
            },
        ),
        migrations.CreateModel(
            name='Winddirection',
            fields=[
                ('starttimewinddir', models.DateTimeField(db_column='startTimeWinddir')),
                ('latitudewinddir', models.FloatField(db_column='latitudeWinddir')),
                ('longitudewinddir', models.FloatField(db_column='longitudeWinddir')),
                ('uwinddir', models.FloatField(db_column='uWinddir')),
                ('vwinddir', models.FloatField(db_column='vWinddir')),
                ('speedwinddir', models.FloatField(db_column='speedWinddir')),
                ('directionwinddir', models.FloatField(db_column='directionWinddir')),
                ('temperaturewinddir', models.FloatField(db_column='temperatureWinddir')),
                ('geopotentialheightwinddir', models.FloatField(db_column='geopotentialHeightWinddir')),
                ('indwinddir', models.IntegerField(blank=True, db_column='indWinddir', null=True)),
                ('statewinddir', models.SmallIntegerField(db_column='stateWinddir')),
                ('datecreationwinddir', models.DateTimeField(auto_now_add=True, db_column='dateCreationWinddir')),
                ('idwinddirection', models.CharField(db_column='idWinddir', max_length=21, primary_key=True, serialize=False)),
                ('idwolcano', models.ForeignKey(blank=True, db_column='idVolcano', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.volcano')),
            ],
            options={
                'db_table': 'WindDirection',
            },
        ),
        migrations.DeleteModel(
            name='Meteorologicaldata',
        ),
    ]
