# Generated by Django 4.2.3 on 2023-11-25 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0053_ashdispersion_ashfallprediction_winddirection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashdispersion',
            name='datecreationmet',
        ),
        migrations.RemoveField(
            model_name='ashdispersion',
            name='statemet',
        ),
        migrations.AddField(
            model_name='ashdispersion',
            name='datecreationashdisp',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationAshdisp', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ashdispersion',
            name='stateashdisp',
            field=models.SmallIntegerField(db_column='stateAshdisp', default=1),
            preserve_default=False,
        ),
    ]
