# Generated by Django 4.2.7 on 2023-11-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0054_remove_ashdispersion_datecreationmet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='starttimestat',
        ),
        migrations.AddField(
            model_name='ashfallprediction',
            name='jsonbodyashfall',
            field=models.JSONField(db_column='jsonbodyAshfall', default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ashfallprediction',
            name='typeashfall',
            field=models.CharField(db_column='typeAshfall', default='000', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mask',
            name='idstation',
            field=models.ForeignKey(db_column='idStation', default='SAB', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertconfiguration',
            name='idalertconf',
            field=models.CharField(blank=True, db_column='idAlertConf', max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ashdispersion',
            name='idtypeashdisp',
            field=models.CharField(choices=[('OBSERVED', ''), ('FORECAST', '')], db_column='idTypeAshdisp', max_length=10),
        ),
    ]
