# Generated by Django 4.2.7 on 2023-11-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0055_remove_station_starttimestat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winddirection',
            old_name='idwolcano',
            new_name='idvolcano',
        ),
        migrations.RemoveField(
            model_name='winddirection',
            name='datecreationwinddir',
        ),
    ]
