# Generated by Django 4.2.7 on 2023-11-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0056_rename_idwolcano_winddirection_idvolcano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashdispersion',
            name='datecreationashdisp',
        ),
        migrations.RemoveField(
            model_name='ashfallprediction',
            name='datecreationashfall',
        ),
        migrations.AlterField(
            model_name='ashdispersion',
            name='stateashdisp',
            field=models.SmallIntegerField(db_column='stateAshdisp', default=1),
        ),
        migrations.AlterField(
            model_name='ashfallprediction',
            name='stateashfall',
            field=models.SmallIntegerField(db_column='stateAshfall', default=1),
        ),
        migrations.AlterField(
            model_name='winddirection',
            name='statewinddir',
            field=models.SmallIntegerField(db_column='stateWinddir', default=1),
        ),
    ]
