# Generated by Django 4.2.8 on 2023-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0057_remove_ashdispersion_datecreationashdisp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='idalert',
            field=models.CharField(db_column='idAlert', max_length=24, primary_key=True, serialize=False),
        ),
    ]
