# Generated by Django 4.2.8 on 2023-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0058_alter_alert_idalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='datecreationalert',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='datecreationalertconf',
        ),
        migrations.AlterField(
            model_name='alert',
            name='idalert',
            field=models.CharField(blank=True, db_column='idAlert', max_length=24, primary_key=True, serialize=False),
        ),
    ]
