# Generated by Django 4.2.8 on 2023-12-12 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0059_remove_alert_datecreationalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='datecreationalert',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationAlert', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='datecreationalertconf',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreationAlertConf', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
