# Generated by Django 4.2.8 on 2023-12-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0060_alert_datecreationalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alertlevelalert',
            field=models.CharField(db_column='alertLevelAlert', default='Alto', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='heighalert',
            field=models.FloatField(db_column='heighAlert', default=48956),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='idstation',
            field=models.ForeignKey(db_column='idStation', default='SAB', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volcano',
            name='alertlevelvol',
            field=models.CharField(choices=[('Medio', ''), ('Bajo', ''), ('Alto', '')], db_column='alertLevelVol', default='Alto', max_length=10),
            preserve_default=False,
        ),
    ]
