# Generated by Django 4.2.7 on 2024-01-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volcanoApp', '0061_alert_alertlevelalert_alert_heighalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='idalertconf',
            field=models.ForeignKey(db_column='idAlertConf', on_delete=django.db.models.deletion.CASCADE, to='volcanoApp.alertconfiguration'),
        ),
        migrations.AlterField(
            model_name='blob',
            name='idmask',
            field=models.ForeignKey(db_column='idMask', on_delete=django.db.models.deletion.CASCADE, to='volcanoApp.mask'),
        ),
        migrations.AlterField(
            model_name='history',
            name='iduser',
            field=models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='idstation',
            field=models.ForeignKey(db_column='idStation', on_delete=django.db.models.deletion.CASCADE, to='volcanoApp.station'),
        ),
        migrations.AlterField(
            model_name='winddirection',
            name='idwinddirection',
            field=models.CharField(db_column='idWinddir', max_length=21, primary_key=True, serialize=False),
        ),
    ]
