# Generated by Django 4.2.7 on 2024-01-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0062_alter_alert_idalertconf_alter_blob_idmask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='idashdispersion',
            field=models.ForeignKey(blank=True, db_column='idAshDispersion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.ashdispersion'),
        ),
        migrations.AddField(
            model_name='alert',
            name='latitudealert',
            field=models.FloatField(blank=True, db_column='latitudeAlert', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitudealert',
            field=models.FloatField(blank=True, db_column='longitudeAlert', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='typealert',
            field=models.SmallIntegerField(db_column='typeAlert', default=0),
            preserve_default=False,
        ),
    ]
