# Generated by Django 4.2.7 on 2024-01-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0063_alert_idashdispersion_alert_latitudealert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='idImgRaw',
            field=models.ForeignKey(db_column='idPhoto', default='SABMRCA20240103095011', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.imagesegmentation'),
            preserve_default=False,
        ),
    ]
