# Generated by Django 4.2.7 on 2024-01-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0064_alert_idimgraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='idImgRaw',
            new_name='idimgraw',
        ),
    ]
