# Generated by Django 4.2.7 on 2024-01-25 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0065_rename_idimgraw_alert_idimgraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='idvolcano',
            field=models.ForeignKey(db_column='idVolcano', default='SAB', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.volcano'),
            preserve_default=False,
        ),
    ]
