# Generated by Django 4.2.7 on 2024-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0067_rename_indtempser_temporaryseries_indtempser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idalarm', models.CharField(db_column='idAlarm', max_length=17)),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('alarmtype', models.CharField(db_column='alarmType', max_length=2)),
                ('sent', models.CharField(max_length=2)),
                ('idexplosion', models.CharField(db_column='idExplosion', max_length=17)),
                ('idvolcano', models.CharField(db_column='idVolcano', max_length=3)),
                ('ind', models.CharField(blank=True, max_length=2, null=True)),
                ('idstation', models.CharField(blank=True, db_column='idStation', max_length=4, null=True)),
            ],
            options={
                'db_table': 'Alarm',
            },
        ),
        migrations.CreateModel(
            name='Explosion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idexplosion', models.CharField(db_column='idExplosion', max_length=17)),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('idevent', models.CharField(db_column='idEvent', max_length=21)),
                ('idimage', models.CharField(blank=True, db_column='idImage', max_length=21, null=True)),
                ('idmask', models.CharField(blank=True, db_column='idMask', max_length=21, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('ashdirection', models.CharField(blank=True, db_column='ashDirection', max_length=30, null=True)),
                ('idwinddir', models.CharField(blank=True, db_column='idWinddir', max_length=19, null=True)),
                ('idashdispersion', models.CharField(blank=True, db_column='idAshDispersion', max_length=17, null=True)),
                ('idashfallprediction', models.CharField(blank=True, db_column='idAshfallprediction', max_length=20, null=True)),
                ('detectionmode', models.CharField(db_column='detectionMode', max_length=2)),
                ('idvolcano', models.CharField(db_column='idVolcano', max_length=3)),
                ('ind', models.CharField(blank=True, max_length=2, null=True)),
                ('idstation', models.CharField(blank=True, db_column='idStation', max_length=4, null=True)),
            ],
            options={
                'db_table': 'Explosion',
            },
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='brightnessTempSer',
            new_name='brightnesstempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='cc1TempSer',
            new_name='cc1tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='cc2TempSer',
            new_name='cc2tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='cc3TempSer',
            new_name='cc3tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='cc4TempSer',
            new_name='cc4tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='cc5TempSer',
            new_name='cc5tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='centralEnergyTempSer',
            new_name='centralenergytempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='entropyTempSer',
            new_name='entropytempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='kurtosisTempSer',
            new_name='kurtosistempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='lpc1TempSer',
            new_name='lpc1tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='lpc2TempSer',
            new_name='lpc2tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='lpc4TempSer',
            new_name='lpc4tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='lpc5TempSer',
            new_name='lpc5tempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='meanKurtosisTempSer',
            new_name='meankurtosistempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='meanSkewnessTempSer',
            new_name='meanskewnesstempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='meanTempSer',
            new_name='meantempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='renyiEntropyTempSer',
            new_name='renyientropytempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='rmsBandwidthTempSer',
            new_name='rmsbandwidthtempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='shannonEntropyTempSer',
            new_name='shannonentropytempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='skewnessTempSer',
            new_name='skewnesstempser',
        ),
        migrations.RenameField(
            model_name='temporaryseries',
            old_name='standardDeviationTempSer',
            new_name='standarddeviationtempser',
        ),
        migrations.RemoveField(
            model_name='temporaryseries',
            name='indTempSer',
        ),
        migrations.RemoveField(
            model_name='temporaryseries',
            name='lpc3TempSer',
        ),
        migrations.RemoveField(
            model_name='temporaryseries',
            name='relativeHeight',
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='attackratiotempser',
            field=models.FloatField(db_column='attackRatioTempSer', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='decayratiotempser',
            field=models.FloatField(db_column='decayRatioTempSer', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='durationtempser',
            field=models.FloatField(db_column='durationTempSer', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='energytempser',
            field=models.FloatField(db_column='energyTempSer', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='freqindextempser',
            field=models.FloatField(db_column='freqIndexTempSer', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='datecreationtempser',
            field=models.DateTimeField(db_column='dateCreationTempSer'),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='ideventtype',
            field=models.CharField(blank=True, db_column='idEventType', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='idstation',
            field=models.CharField(db_column='idStation', max_length=5),
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='indtempser',
            field=models.IntegerField(blank=True, db_column='indTempSer', null=True),
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='lpc3tempser',
            field=models.FloatField(db_column='lpc3TempSer', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryseries',
            name='relativeheight',
            field=models.CharField(blank=True, db_column='relativeHeight', null=True),
        ),
    ]
