# Generated by Django 4.2.7 on 2024-03-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0068_alarm_explosion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='explosion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='explosion',
            name='idevent',
        ),
        migrations.RemoveField(
            model_name='explosion',
            name='idmask',
        ),
        migrations.AddField(
            model_name='explosion',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explosion',
            name='ideventtype',
            field=models.ForeignKey(blank=True, db_column='idEvent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.eventtype'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='idalarm',
            field=models.CharField(blank=True, db_column='idAlarm', max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='idexplosion',
            field=models.ForeignKey(db_column='idExplosion', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.explosion'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='idstation',
            field=models.ForeignKey(blank=True, db_column='idStation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.station'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='idvolcano',
            field=models.ForeignKey(db_column='idVolcano', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.volcano'),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='idashdispersion',
            field=models.ForeignKey(blank=True, db_column='idAshDispersion', max_length=17, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.ashdispersion'),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='idashfallprediction',
            field=models.ForeignKey(blank=True, db_column='idAshfallprediction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.ashfallprediction'),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='idexplosion',
            field=models.CharField(blank=True, db_column='idExplosion', max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='idimage',
            field=models.ForeignKey(blank=True, db_column='idImage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.imagesegmentation'),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='idstation',
            field=models.ForeignKey(blank=True, db_column='idStation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.station'),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='idvolcano',
            field=models.ForeignKey(db_column='idVolcano', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.volcano'),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='idwinddir',
            field=models.ForeignKey(blank=True, db_column='idWinddir', max_length=19, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.winddirection'),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='ideventtype',
            field=models.ForeignKey(blank=True, db_column='idEventType', max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.eventtype'),
        ),
        migrations.AlterField(
            model_name='temporaryseries',
            name='idstation',
            field=models.ForeignKey(db_column='idStation', on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.station'),
        ),
    ]
