# Generated by Django 4.2.7 on 2024-03-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0069_remove_alarm_id_remove_explosion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfiguration',
            name='idvolcano',
            field=models.OneToOneField(blank=True, db_column='idVolcano', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configuration', to='volcanoApp.volcano'),
        ),
    ]
