# Generated by Django 4.2.7 on 2024-03-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0070_alter_alertconfiguration_idvolcano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='startalert',
        ),
        migrations.AlterField(
            model_name='alert',
            name='idimgraw',
            field=models.ForeignKey(blank=True, db_column='idPhoto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volcanoApp.imagesegmentation'),
        ),
    ]
