# Generated by Django 4.2.7 on 2024-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0071_remove_alert_startalert_alter_alert_idimgraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesegmentation',
            name='stateimg',
            field=models.SmallIntegerField(blank=True, db_column='stateImg'),
        ),
    ]
