# Generated by Django 4.2.7 on 2024-03-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0073_alter_imagesegmentation_stateimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesegmentation',
            name='stateimg',
        ),
    ]
