# Generated by Django 4.2.7 on 2024-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0074_remove_imagesegmentation_stateimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesegmentation',
            name='stateimg',
            field=models.SmallIntegerField(db_column='stateImg', default=1),
            preserve_default=False,
        ),
    ]
