# Generated by Django 4.2.7 on 2024-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoApp', '0076_remove_mask_statemask'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='statemask',
            field=models.SmallIntegerField(db_column='statemask', default=1),
            preserve_default=False,
        ),
    ]
